# Generated by Django 2.1.4 on 2018-12-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20181213_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
